# ----------- Sensor ----------- #
sensor:
  - platform:               modbus_controller
    name:                   ${name} ${channel_02_friendly_name} Temperatur
    id:                     ${device}_${channel_02_id}_temperatur
    modbus_controller_id:   ${device}_modbus_controller
    custom_command: 
      - 0x01
      - 0x43
      - 0x01
      - 0x04
      - $channel_02_sensor
      - 0x01
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    force_update: True
    filters:
      - multiply: 0.1
  # Battery
  - platform:               modbus_controller
    name:                   ${name} ${channel_02_friendly_name} Batteri
    id:                     ${device}_${channel_02_id}_batteri
    modbus_controller_id:   ${device}_modbus_controller
    custom_command: 
      - 0x01
      - 0x43
      - 0x01
      - 0x0A
      - $channel_02_sensor
      - 0x01
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 0
    device_class: battery
    filters:
      - multiply: 10 

# ----------- Binary ----------- #
binary_sensor:
  - platform:               modbus_controller
    name:                   ${name} ${channel_02_friendly_name} Aktiv
    id:                     ${device}_${channel_02_id}_aktiv
    modbus_controller_id:   ${device}_modbus_controller
    custom_command:
      - 0x01
      - 0x43
      - 0x03
      - 0x00
      - $channel_02
      - 0x01
    bitmask: 0x0010

# ----------- Number ----------- #
number:
  - platform:               modbus_controller
    name:                   ${name} ${channel_02_friendly_name} Måltemperatur
    id:                     ${device}_${channel_02_id}_maaltemperatur
    modbus_controller_id:   ${device}_modbus_controller
    custom_command: 
      - 0x01
      - 0x43
      - 0x02
      - 0x00
      - $channel_02
      - 0x01
    value_type: U_WORD
    unit_of_measurement: "°C"
    min_value: 6
    max_value: 40
    step: .5
    write_lambda: |-
      ESP_LOGD("main", "Trying to write new target temp: %f",x);
      uint16_t targettemp = x * 10;
      payload.push_back(0x0144);
      payload.push_back(0x0200);
      payload.push_back(${channel_02}01);
      payload.push_back(targettemp);
      return true;
    lambda: "return x*0.1;"

# ----------- Switch ----------- #
switch:
  - platform:               modbus_controller
    name:                   ${name} ${channel_02_friendly_name} Standby
    id:                     ${device}_${channel_02_id}_standby
    modbus_controller_id:   ${device}_modbus_controller
    custom_command:
      - 0x01
      - 0x43
      - 0x02
      - 0x07
      - $channel_02
      - 0x01
    write_lambda: |-
      ESP_LOGD("main","Modbus Switch incoming state for channel 02 = %s",ONOFF(x));
      bool state = ONOFF(x);
      uint8_t MODE_MASK = 0x07;
      payload.push_back(0x01);
      payload.push_back(0x45);
      payload.push_back(0x02);
      payload.push_back(0x07); 
      payload.push_back(${channel_02});       
      payload.push_back(0x01); 
      if(x)
      {
        ESP_LOGD("main","Pushing back 0x01 because state is %s",ONOFF(x));
        payload.push_back( 0x01 >> 8);
        payload.push_back( 0x01 & 0xFF);
      }
      else
      {
        ESP_LOGD("main","Pushing back 0x00 because state is %s",ONOFF(x));
        payload.push_back( 0x00 >> 8);
        payload.push_back( 0x00 & 0xFF);
      }
      payload.push_back((~MODE_MASK) >> 8);
      payload.push_back((~MODE_MASK) & 0xFF);
      return true;
    lambda: |-
      int mode = data[1];
      ESP_LOGD("main","MODE for Channel 02 is: %i",mode);    
      return mode;

# ----------- Climate ----------- #
climate:
  - platform:               wavinahc9000v2
    name:                   ${name} ${channel_02_friendly_name}
    current_temp_sensor_id: ${device}_${channel_02_id}_temperatur
    target_temp_number_id:  ${device}_${channel_02_id}_maaltemperatur
    mode_switch_sensor_id:  ${device}_${channel_02_id}_standby
    action_sensor_id:       ${device}_${channel_02_id}_aktiv
